#
# Defines environment variables.

PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

. "$HOME/.cargo/env"

export EDITOR=vim
export VISUAL=vim

# uv
export PATH="/Users/xiaotian/.local/bin:$PATH"
