#
# Defines environment variables.

PATH="/opt/homebrew/bin:$PATH"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

export EDITOR=vim
export VISUAL=vim

# uv
export PATH="$HOME/.local/bin:$PATH"
